<?php

namespace ContainerMSixfFe;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriasControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CategoriasController' shared autowired service.
     *
     * @return \App\Controller\CategoriasController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'CategoriasController.php';

        return $container->services['App\\Controller\\CategoriasController'] = new \App\Controller\CategoriasController(($container->privates['App\\Repository\\CategoriasRepository'] ?? $container->load('getCategoriasRepositoryService')));
    }
}
