<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerICC4nFO\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerICC4nFO/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerICC4nFO.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerICC4nFO\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerICC4nFO\App_KernelProdContainer([
    'container.build_hash' => 'ICC4nFO',
    'container.build_id' => '157d2624',
    'container.build_time' => 1613378460,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerICC4nFO');
