<?php

namespace ContainerLZNix19;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubcategoriasControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SubcategoriasController' shared autowired service.
     *
     * @return \App\Controller\SubcategoriasController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'SubcategoriasController.php';

        return $container->services['App\\Controller\\SubcategoriasController'] = new \App\Controller\SubcategoriasController(($container->privates['App\\Repository\\SubcategoriasRepository'] ?? $container->load('getSubcategoriasRepositoryService')));
    }
}
