<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKdnDRtO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKdnDRtO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKdnDRtO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKdnDRtO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKdnDRtO\App_KernelDevDebugContainer([
    'container.build_hash' => 'KdnDRtO',
    'container.build_id' => 'e1c69ad2',
    'container.build_time' => 1613420265,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKdnDRtO');
