<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHFICbaW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHFICbaW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHFICbaW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHFICbaW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHFICbaW\App_KernelDevDebugContainer([
    'container.build_hash' => 'HFICbaW',
    'container.build_id' => '30c39604',
    'container.build_time' => 1613548671,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHFICbaW');
