<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSi6d7Gf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSi6d7Gf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSi6d7Gf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSi6d7Gf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSi6d7Gf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Si6d7Gf',
    'container.build_id' => 'fddbae77',
    'container.build_time' => 1613128189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSi6d7Gf');
