<?php

namespace ContainerIgVnnU9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductosControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ProductosController' shared autowired service.
     *
     * @return \App\Controller\ProductosController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ProductosController.php';

        return $container->services['App\\Controller\\ProductosController'] = new \App\Controller\ProductosController(($container->privates['App\\Repository\\ProductosRepository'] ?? $container->load('getProductosRepositoryService')));
    }
}
