<?php

namespace ContainerICC4nFO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMensajesRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MensajesRepository' shared autowired service.
     *
     * @return \App\Repository\MensajesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MensajesRepository'] = new \App\Repository\MensajesRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
