<?php

namespace ContainerICC4nFO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductosControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ProductosController' shared autowired service.
     *
     * @return \App\Controller\ProductosController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\ProductosController'] = new \App\Controller\ProductosController(($container->privates['App\\Repository\\ProductosRepository'] ?? $container->load('getProductosRepositoryService')));
    }
}
