<?php

namespace ContainerICC4nFO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_Listener_Json_MainService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.authentication.listener.json.main' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\UsernamePasswordJsonAuthenticationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor();

        $container->privates['security.authentication.listener.json.main'] = $instance = new \Symfony\Component\Security\Http\Firewall\UsernamePasswordJsonAuthenticationListener(($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->privates['security.authentication.manager'] ?? $container->load('getSecurity_Authentication_ManagerService')), ($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService')), 'main', NULL, NULL, ['check_path' => '/login', 'use_forward' => false, 'require_previous_session' => false, 'login_path' => '/login', 'username_path' => 'username', 'password_path' => 'password'], ($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), new \Symfony\Component\PropertyAccess\PropertyAccessor(3, false, ($container->privates['cache.property_access'] ?? $container->load('getCache_PropertyAccessService')), true, $a, $a));

        $instance->setSessionAuthenticationStrategy(new \Symfony\Component\Security\Http\Session\SessionAuthenticationStrategy('migrate'));

        return $instance;
    }
}
