<?php

namespace ContainerICC4nFO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuariosControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\UsuariosController' shared autowired service.
     *
     * @return \App\Controller\UsuariosController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\UsuariosController'] = new \App\Controller\UsuariosController(($container->privates['App\\Repository\\UsuariosRepository'] ?? $container->load('getUsuariosRepositoryService')));
    }
}
